import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker,{validState} from '../worker/index.js';
const secret='private-test-password-never-deploy';
function environment(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8'));return {ORBITA_PASSWORD:secret,DB:{prepare(sql){return {bind(...args){return {async first(){return db.prepare(sql).get(...args)||null;},async run(){const result=db.prepare(sql).run(...args);return {meta:{changes:result.changes}};}}},async first(){return db.prepare(sql).get()||null;}};}}};}
function req(path,method='GET',body,cookie='',origin='https://orbita.test'){return new Request('https://orbita.test/api/'+path,{method,headers:{origin,'content-type':'application/json',cookie},...(body?{body:JSON.stringify(body)}:{})});}
const empty=()=>({places:[],habits:[],tasks:[],entries:[]});
test('private state requires session; login rejects bad passwords and cross-origin writes',async()=>{const env=environment();assert.equal((await worker.fetch(req('state'),env)).status,401);assert.equal((await worker.fetch(req('login','POST',{password:'wrong'}),env)).status,401);assert.equal((await worker.fetch(req('login','POST',{password:secret},'','https://evil.test'),env)).status,403);const res=await worker.fetch(req('login','POST',{password:secret}),env);assert.equal(res.status,200);assert.match(res.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);});
test('saves survive reads and simultaneous device edits cannot overwrite one another',async()=>{const env=environment();const login=await worker.fetch(req('login','POST',{password:secret}),env);const cookie=login.headers.get('set-cookie').split(';')[0];const state=empty();state.tasks.push({id:'task-1',title:'Ir al gym',done:false,priority:'normal',due:''});const response=await worker.fetch(req('state','PUT',{state,revision:0},cookie),env);assert.equal(response.status,200);assert.equal((await response.json()).revision,1);assert.deepEqual((await(await worker.fetch(req('state','GET',null,cookie),env)).json()).state,state);assert.equal((await worker.fetch(req('state','PUT',{state:empty(),revision:0},cookie),env)).status,409);const read=await(await worker.fetch(req('state','GET',null,cookie),env)).json();assert.equal(read.state.tasks.length,1);});
test('invalid geometry, dates, and injection-prone identifiers are rejected',()=>{let s=empty();s.places.push({id:'a',name:'Barcelona',country:'España',lat:41.4,lng:2.17,date:'2026-10-04',note:''});assert.ok(validState(s));s.places[0].lat=91;assert.equal(validState(s),false);s.places[0].lat=41;s.places[0].date='2026-02-31';assert.equal(validState(s),false);s.places[0].date='2026-10-04';s.places[0].id='" onclick="evil';assert.equal(validState(s),false);});
test('login rate limiting and missing secret fail closed',async()=>{const env=environment();for(let i=0;i<10;i++)assert.equal((await worker.fetch(req('login','POST',{password:'wrong'}),env)).status,401);assert.equal((await worker.fetch(req('login','POST',{password:secret}),env)).status,429);env.ORBITA_PASSWORD='';assert.equal((await worker.fetch(req('state'),env)).status,503);assert.deepEqual(await(await worker.fetch(req('session'),env)).json(),{configured:false,authenticated:false});});
