CREATE TABLE IF NOT EXISTS push_config (id INTEGER PRIMARY KEY CHECK(id = 1), data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS push_subscriptions (endpoint TEXT PRIMARY KEY, data TEXT NOT NULL, last_day TEXT NOT NULL DEFAULT '', last_test INTEGER NOT NULL DEFAULT 0);
